version: '3.3'

# ************************************************************
# *                  VOLUMES                                 *
# ************************************************************
volumes:
    api_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: ${DIR}/backend/api
    database:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: ${DIR}/backend/database/data


# ************************************************************
# *                  NETWORK                                 *
# ************************************************************
networks:
    api_network:

# ************************************************************
# *                  SERVICES                                *
# ************************************************************
services:
    # *******************API*******************
    api:
        container_name: api
        image: api:latest
        build:
            context: ./backend
            dockerfile: api.Dockerfile
        restart: always
        volumes:
            - api_volume:/home/api
        ports:
            - ${SERVER_PORT_BACK}:${SERVER_PORT_BACK}
        env_file:
          - .env
        networks:
            - api_network
        depends_on:
            - database
    # *******************FRONTEND*******************
    frontend:
        container_name: frontend
        image: frontend:latest
        build:
            context: ./frontend
        restart: always
        volumes:
          - ./frontend/:/usr/frontend/app
          - /usr/frontend/app/node_modules
        ports:
            - ${SERVER_PORT_FRONT}:${SERVER_PORT_FRONT}
        env_file:
          - .env
        networks:
            - api_network
        depends_on:
            - api

    # *******************DATABASE*******************
    database:
        container_name: postgres
        image: postgres:latest
        command: postgres -c stats_temp_directory=/tmp
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
            - ${DIR}/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - api_network

    # *******************ADMINER*******************
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:${ADMINER_PORT}
        networks:
            - api_network
        depends_on:
            - database
