version: '3.7'

# ************************************************************
# *                  VOLUMES                                 *
# ************************************************************
volumes:
    database:

# ************************************************************
# *                  NETWORK                                 *
# ************************************************************
networks:
    api_network:

# ************************************************************
# *                  SERVICES                                *
# ************************************************************
services:
    # *******************API*******************
    api:
        container_name: backend
        image: backend:latest
        build:
            context: ./backend/api
        restart: always
        volumes:
          - ./backend/api/:/usr/src/app
          - /usr/src/app/node_modules
        ports:
            - ${SERVER_PORT_BACK}:${SERVER_PORT_BACK}
        command: npm run start:dev
        env_file:
          - .env
        networks:
            - api_network
        depends_on:
            - database

    # *******************FRONTEND*******************
    frontend:
        container_name: frontend
        image: frontend:latest
        build:
            context: ./frontend
        restart: always
        volumes:
          - ./frontend/:/usr/src/app
          - /usr/src/app/node_modules
        ports:
            - ${SERVER_PORT_FRONT}:${SERVER_PORT_FRONT}
        command: npm run dev
        env_file:
          - .env
        networks:
            - api_network
        depends_on:
            - api

    # *******************DATABASE*******************
    database:
        container_name: postgres
        image: postgres:latest
        command: postgres -c stats_temp_directory=/tmp
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
        networks:
            - api_network

    # *******************ADMINER*******************
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080
        networks:
            - api_network
        depends_on:
            - database
